# Use postgres/example user/password credentials
version: '3.7'

services:

  pg:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
